---
- name: Ensure Docker-Compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Create a directory for container config storage
  ansible.builtin.file:
    path: "/opt/stacks/{{ APP }}/config"
    state: directory
    mode: '0755'
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Create a directory for container data storage
  ansible.builtin.file:
    path: "/opt/stacks/{{ APP }}/data"
    state: directory
    mode: '0755'
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Create a directory for container dashboard storage
  ansible.builtin.file:
    path: "/opt/stacks/{{ APP }}/dashboards"
    state: directory
    mode: '0755'
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Create a directory for container provisioning storage
  ansible.builtin.file:
    path: "/opt/stacks/{{ APP }}/provisioning"
    state: directory
    mode: '0755'
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Create a directory for container provisioning-alerting storage
  ansible.builtin.file:
    path: "/opt/stacks/{{ APP }}/provisioning/alerting"
    state: directory
    mode: '0755'
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Create a directory for container provisioning-dashboards storage
  ansible.builtin.file:
    path: "/opt/stacks/{{ APP }}/provisioning/dashboards"
    state: directory
    mode: '0755'
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Create a directory for container provisioning-datasources storage
  ansible.builtin.file:
    path: "/opt/stacks/{{ APP }}/provisioning/datasources"
    state: directory
    mode: '0755'
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Create a directory for container provisioning-plugins storage
  ansible.builtin.file:
    path: "/opt/stacks/{{ APP }}/provisioning/plugins"
    state: directory
    mode: '0755'
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Add config file
  ansible.builtin.copy:
    src: "files/grafana.ini"
    dest: "/opt/stacks/{{ APP }}/config/grafana.ini"
    mode: '0644'
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Add dashboards config file
  ansible.builtin.copy:
    src: "files/dashboards.yaml"
    dest: "/opt/stacks/{{ APP }}/provisioning/dashboards/dashboards.yaml"
    mode: '0644'
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Add datasources config file
  ansible.builtin.copy:
    src: "files/datasources.yaml"
    dest: "/opt/stacks/{{ APP }}/provisioning/datasources/datasources.yaml"
    mode: '0644'
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Add docker dashboard file
  ansible.builtin.copy:
    src: "files/docker.json"
    dest: "/opt/stacks/{{ APP }}/dashboards/docker.json"
    mode: '0644'
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Add compose file
  ansible.builtin.template:
    src: "templates/compose.yaml.j2"
    dest: "/opt/stacks/{{ APP }}/compose.yaml"
    mode: '0644'
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Check if image exists
  community.docker.docker_image:
    name: "{{ IMAGE_NAME }}"
    tag: "{{ IMAGE_TAG }}"
    source: pull

- name: Start container
  community.docker.docker_compose_v2:
    project_src: "/opt/stacks/{{ APP }}/"
    state: present
