#cd $HOME/Documents/Tech/Configuration/Ansible-Playbook/server/update
#ansible-playbook playbook.yaml -i inventory.yaml --ask-become-pass --key-file $HOME/.ssh/id_ed25519

---
- name: Server Update
  hosts: bare_metal:virtual_machines
  vars_files:
    - vars/main.yaml
  tasks:
    - ansible.builtin.import_tasks: tasks/main.yaml
  handlers:
    - ansible.builtin.import_tasks: handlers/main.yaml