# ansible-vault encrypt /Users/troy/Documents/Tech/Configuration/Ansible-Playbook/docker/docker_install/vars/main.yaml
# ansible-vault decrypt /Users/troy/Documents/Tech/Configuration/Ansible-Playbook/docker/docker_install/vars/main.yaml

# cd $HOME/Documents/Tech/Configuration/Ansible-Playbook/docker
# ansible-playbook --ask-vault-password playbook.yaml -i inventory.yaml --ask-become-pass --key-file $HOME/.ssh/id_ed25519
# ansible-playbook --ask-vault-password playbook.yaml -i inventory.yaml

---
- name: Install Docker Homelab
  hosts: virtual_machines
  become: true
  roles:
    - docker_install
    # - alloy_deploy
    # - audiobookshelf_deploy
    # - bazarr_deploy
    - dozzle_deploy
    - filebrowser_deploy
    # - gatus_deploy
    # - ghost_deploy
    # - gotify_deploy
    # - grafana_deploy
    # - homepage_deploy
    # - jellyfin_deploy
    # - jellystat_deploy
    # - loki_deploy
    # - memos_deploy
    # - mkvtoolnix_deploy
    # - myspeed_deploy
    # - photoprism_deploy
    # - plex_deploy
    # - postgres_deploy
    # - prometheus_deploy
    # - prowlarr_deploy
    # - radarr_deploy
    # - seerr_deploy
    # - sonarr_deploy
    # - tautulli_deploy
    # - technitium_deploy
    # - telegraf_deploy
    # - transmission_deploy
    # - umami_deploy
    # - vaultwarden_deploy
