[agent]
  hostname = "telegraf-host"
  interval = "10s"
  flush_interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_jitter = "0s"
  precision = ""
  logfile = ""
  debug = false
  quiet = false
  omit_hostname = false
  skip_processors_after_aggregators = false

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  gather_services = false
  source_tag = false
  timeout = "15s"
  docker_label_include = []
  docker_label_exclude = [
    "org.opencontainers.*",
    "com.docker.*",
    "desktop.docker.*"
  ]

[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2
