---
- name: Ensure Docker-Compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Create a directory for container storage
  ansible.builtin.file:
    path: "/opt/stacks/{{ APP }}"
    state: directory
    mode: '0755'
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Create a directory for container consume storage
  ansible.builtin.file:
    path: "/opt/stacks/{{ APP }}/consume"
    state: directory
    mode: '0777'
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Create a directory for container data storage
  ansible.builtin.file:
    path: "/opt/stacks/{{ APP }}/data"
    state: directory
    mode: '0777'
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Create a directory for container export storage
  ansible.builtin.file:
    path: "/opt/stacks/{{ APP }}/export"
    state: directory
    mode: '0777'
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Create a directory for container media storage
  ansible.builtin.file:
    path: "/opt/stacks/{{ APP }}/media"
    state: directory
    mode: '0777'
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Add compose file
  ansible.builtin.template:
    src: "templates/compose.yaml.j2"
    dest: "/opt/stacks/{{ APP }}/compose.yaml"
    mode: '0644'
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Add env file
  ansible.builtin.template:
    src: "templates/env.j2"
    dest: "/opt/stacks/{{ APP }}/.env"
    mode: '0644'
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Check if image exists
  community.docker.docker_image:
    name: "{{ IMAGE_NAME }}"
    tag: "{{ IMAGE_TAG }}"
    source: pull

- name: Wait for Redis to be running
  community.docker.docker_container_info:
    name: redis
  register: redis_info
  until: redis_info.exists and redis_info.container.State.Status == "running"
  retries: 30
  delay: 10
  failed_when: false

- name: Check if Redis is running
  ansible.builtin.fail:
    msg: "Redis container not running. Cannot proceed with deployment."
  when: not redis_info.exists or redis_info.container.State.Status != "running"

- name: Start container
  community.docker.docker_compose_v2:
    project_src: "/opt/stacks/{{ APP }}"
    state: present
