---
ufw_allowed_ports:
  - {port: 22, proto: tcp, comment: 'SSH'}
  - {port: 53, proto: tcp, comment: 'DNS'}
  - {port: 53, proto: udp, comment: 'DNS'}
  - {port: 80, proto: tcp, comment: 'HTTP'}
  - {port: 443, proto: tcp, comment: 'HTTPS'}
  # - {port: 12345, proto: tcp, comment: 'Alloy'}
  # - {port: 13378, proto: tcp, comment: 'Audiobookshelf'}
  # - {port: 21027, proto: udp, comment: 'Syncthing'}
  # - {port: 22000, proto: tcp, comment: 'Syncthing'}
  # - {port: 22000, proto: udp, comment: 'Syncthing'}
  # - {port: 2368, proto: tcp, comment: 'Ghost'}
  # - {port: 3000, proto: tcp, comment: 'Gitea'}
  # - {port: 3000, proto: tcp, comment: 'Homepage'}
  # - {port: 3100, proto: tcp, comment: 'Loki'}
  # - {port: 3200, proto: udp, comment: 'Tempo'}
  # - {port: 3210, proto: tcp, comment: 'Umami'}
  # - {port: 32400, proto: tcp, comment: 'Plex'}
  # - {port: 3333, proto: tcp, comment: 'Grafana'}
  # - {port: 4317, proto: udp, comment: 'Tempo'}
  # - {port: 4318, proto: udp, comment: 'Tempo'}
  # - {port: 5000, proto: tcp, comment: 'Kavita'}
  # - {port: 5055, proto: tcp, comment: 'Seerr'}
  # - {port: 51413, proto: tcp, comment: 'Transmission'}
  # - {port: 51413, proto: udp, comment: 'Transmission'}
  # - {port: 5216, proto: tcp, comment: 'MySpeed'}
  # - {port: 5230, proto: tcp, comment: 'Memos'}
  # - {port: 5800, proto: tcp, comment: 'MKVToolNix'}
  # - {port: 6379, proto: tcp, comment: 'Redis'}
  # - {port: 6767, proto: tcp, comment: 'Bazarr'}
  # - {port: 7878, proto: tcp, comment: 'Radarr'}
  # - {port: 8000, proto: tcp, comment: 'Paperless-ngx'}
  # - {port: 8001, proto: tcp, comment: 'Gotify'}
  - {port: 8005, proto: tcp, comment: 'Filebrowser'}
  - {port: 8008, proto: tcp, comment: 'Dozzle'}
  # - {port: 8096, proto: tcp, comment: 'Jellyfin'}
  # - {port: 8125, proto: tcp, comment: 'Telegraf'}
  # - {port: 8181, proto: tcp, comment: 'Tautulli'}
  # - {port: 8384, proto: tcp, comment: 'Syncthing'}
  # - {port: 8877, proto: tcp, comment: 'Vaultwarden'}
  # - {port: 8989, proto: tcp, comment: 'Sonarr'}
  # - {port: 9090, proto: tcp, comment: 'Prometheus'}
  # - {port: 9091, proto: tcp, comment: 'Transmission'}
  # - {port: 9273, proto: tcp, comment: 'Telegraf'}
  # - {port: 9696, proto: tcp, comment: 'Prowlarr'}
