#cd $HOME/Documents/Tech/Ansible-Playbook/debian/server_update
#
#ansible-playbook playbook.yaml -i inventory.yaml --key-file $HOME/.ssh/id_ed25519

---
- name: Server Update
  hosts: virtual_machines
  vars_files:
    - vars/main.yaml
  tasks:
    - ansible.builtin.import_tasks: tasks/main.yaml
  handlers:
    - ansible.builtin.import_tasks: handlers/main.yaml