{
 "title": "Podman Exporter",
 "description": "Podman Exporter Dashboard",
 "tags": [
  "prometheus",
  "podman-exporter",
  "podman"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Host",
    "query": {
     "query": "label_values(podman_container_info,instance)"
    }
   },
   {
    "name": "name",
    "label": "Container",
    "query": {
     "query": "label_values(podman_container_info{instance=~\"$instance\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (podman_container_info{instance=~'$instance', name=~\"$name\"} * on(id) group_right (name) rate(podman_container_cpu_seconds_total[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by (name) (\n    podman_container_info{instance=~\"$instance\", name=~\"$name\"}\n  * on (id) group_right (name)\n    (podman_container_mem_usage_bytes / 1024 / 1024)\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum by(name) (podman_container_info{instance=~\"$instance\", name=~\"$name\"} * on(id) group_right(name) rate(podman_container_net_input_total[1m]) / 1024)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum by(name) (podman_container_info{instance=~\"$instance\", name=~\"$name\"} * on(id) group_right(name) rate(podman_container_net_output_total[1m]) / 1024)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "podman_container_info{instance=~\"$instance\", name=~\"$name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(podman_container_info{instance=~\"$instance\", name=~\"$name\"} * on (id) group_right (name) (podman_container_state))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(podman_container_info{instance=~\"$instance\", name=~\"$name\"} * on (id) group_right (name) (podman_container_mem_usage_bytes))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(podman_container_info{instance=~\"$instance\", name=~\"$name\"} * on (id) group_right (name) (podman_container_exit_code))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(podman_container_info{instance=~\"$instance\", name=~\"$name\"} * on (id) group_right (name) (time() - podman_container_started_seconds))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(podman_container_info{instance=~\"$instance\", name=~\"$name\"} * on (id) group_right (name) (podman_container_pids))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(podman_container_info{instance=~\"$instance\", name=~\"$name\"} * on (id) group_right (name) (podman_container_mem_usage_bytes / (podman_container_mem_limit_bytes)))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}