{
 "title": "Docker",
 "description": "Prometheus Telegraf Docker Dashboard",
 "tags": [
  "docker",
  "prometheus",
  "telegraf"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(docker_container_cpu_usage_percent, container_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "docker_n_cpus" }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "docker_memory_total" }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "docker_n_containers_running" }
   ]
  },
  {
   "title": "Paused Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "docker_n_containers_paused" }
   ]
  },
  {
   "title": "Stopped Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "docker_n_containers_stopped" }
   ]
  },
  {
   "title": "Images",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "docker_n_images" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (container_name) (docker_container_cpu_usage_percent{container_name=~\"$container\", cpu=\"cpu-total\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (container_name) (docker_container_mem_usage{container_name=~\"$container\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (container_name) (rate(docker_container_blkio_io_service_bytes_recursive_read{container_name=~\"$container\"}[2m]))",
     "legendFormat": "{{container_name}} read"
    },
    {
     "expr": "sum by (container_name) (rate(docker_container_blkio_io_service_bytes_recursive_write{container_name=~\"$container\"}[2m]))",
     "legendFormat": "{{container_name}} write"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (container_name) (rate(docker_container_net_rx_bytes{container_name=~\"$container\"}[2m]))",
     "legendFormat": "{{container_name}} rx"
    },
    {
     "expr": "sum by (container_name) (rate(docker_container_net_tx_bytes{container_name=~\"$container\"}[2m]))",
     "legendFormat": "{{container_name}} tx"
    }
   ]
  }
 ]
}